### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by Kisahime** [wAIfu-DEV/w-AI-fu#22]
Hello, was just letting the program run and after about 10 minutes this error came up,

python TTS:
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002951F0BC3A0>

python TTS:
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002951F015A80>, 16785.234)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002951F0BC820>

python TTS:
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002951F0BC340>
transport: <_ProactorSocketTransport fd=-1 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 365, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 401, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'

python TTS:
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x00000295189D6A70>
Traceback (most recent call last):
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 321, in __del__
    self.close()
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 316, in close

python TTS:
    self._ssl_protocol._start_shutdown()
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 599, in _start_shutdown
    self._write_appdata(b'')
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 604, in _write_appdata

python TTS:
    self._process_write_backlog()
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 712, in _process_write_backlog

python TTS:
    self._fatal_error(exc, 'Fatal error on SSL transport')
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 726, in _fatal_error
    self._transport._force_close(exc)
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 152, in _force_close

python TTS:
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 753, in call_soon

python TTS:
    self._check_closed()
  File "C:\Users\MissS\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed

python TTS:
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by wAIfu-DEV** [comment]
Did the program continue running without issue after this?
If yes then I am aware of this, and have absolutely no idea how to fix it

**Comment by Kisahime** [comment]
> 

it worked again after i did the !reload command and continued to work fine for the duration of the stream, perhaps it's an issue with the aiohttp library?

**Comment by wAIfu-DEV** [comment]
I'm guessing it is but there is litterally no documentation on the error. I think it might be linked to the fact that I am calling async functions using Flask.

**Comment by Kisahime** [comment]
not sure if this helps

Unclosed client session and Unclosed connector: These are issues with the aiohttp library, which is used for handling HTTP requests. This error is usually thrown when the ClientSession isn't properly closed after being used. The correct way to use ClientSession is inside a context manager (a with block), so that it gets automatically closed even if an error occurs. The same goes for the connector.

Fatal error on SSL transport and Event loop is closed: These errors are related to Python's asyncio library, which is used for handling asynchronous I/O operations. These errors suggest that an SSL operation was initiated on a socket transport that has been closed, or a shutdown operation was attempted on an already closed event loop. It is crucial to properly manage the event loop, ensuring it is closed only after all tasks have been completed.

You could have a look at the section of your code where you close the event loop and handle connections. Make sure the event loop is not being closed prematurely and all connections are properly cleaned up.

**Comment by wAIfu-DEV** [comment]
Thanks, I'll comb the code to see where this might happen

**Comment by wAIfu-DEV** [comment]
Not fixed but the issue didn't pop up in a long time.
Will have to wait a bit more to see
