### ISSUE TITLE
run error after install

### ISSUE THREAD

**Issue by joireum** [wAIfu-DEV/w-AI-fu#55]
w-AI-fu 1.2.9
Loading config informations ...
Loading character "Hilda" ...
Loading filter ...
Getting audio devices ...
Spawning subprocesses ...
python TTS:
�׼��� ���ѿ� ���� ������ ���Ͽ� �׼����� �õ��߽��ϴ�

Loaded LLM.
Critical Error: Could not contact TTS python script after 10s
Killing subprocesses ...
Exiting w.AI.fu

how could i fix it?

**Comment by joireum** [comment]
and this is test mode.

Entering TEST mode ...
Checking LLM response ...
python LLM:
Traceback (most recent call last):
  File "C:\Users\joire\Desktop\Downloads\w-AI-fu main\w-AI-fu\novel\novel_llm.py", line 17, in <module>

python LLM:
    from flask import Flask, request, jsonify
  File "C:\Users\joire\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "C:\Users\joire\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (C:\Users\joire\AppData\Local\Programs\Python\Python310\lib\site-packages\werkzeug\urls.py)

> Critical Error: Could not contact LLM python script after 10s
Killing subprocesses ...
Exiting w.AI.fu

**Comment by xlvlx** [comment]
pip install Werkzeug==2.2.2
